# Generated by Django 2.2.12 on 2020-07-25 18:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userauthentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.ForeignKey(help_text='User Created', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
